version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    working_directory: ~/jsmcreserveapp
    steps:
      - checkout:
          path: ~/jsmcreserveapp
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.5
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: JSMCreserveapp_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/jsmcreserveapp
    steps:
      - checkout:
          path: ~/jsmcreserveapp
      - ruby/install-deps
      - run: bundle exec rake assets:precompile
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: rspec
          command: |
            bundle exec rspec --out test_results/rspec.xml \
                              --format documentation
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build